# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KeepCompany' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeepCompany
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase'
pod 'Firebase/Firestore'

  target 'KeepCompanyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeepCompanyUITests' do
    # Pods for testing
  end

end
